name: build uvdesk_
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - uvdesk/*
jobs:
  push:
    name: "spoopy2023/andromeda-dockerfiles:uvdesk_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - desk
    steps:
      - uses: actions/checkout@v3
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHRC }}
      - uses: docker/build-push-action@v4
        with:
          context: ./uvdesk
          file: ./uvdesk/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
             ghcr.io/spoopy2023/andromeda-dockerfiles:uvdesk_${{ matrix.tag }}